
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp
  labels:
    app: dotnetapp
spec:
  selector:
    matchLabels:
      app: dotnetapp
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dotnetapp
        tier: frontend
    spec:
      containers:
      - name: docker-compose-dotnet-core-and-mssql-app
        image: ivansegura/frontend:2.0
        ports:
        - containerPort: 80
