
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teatro-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
        - name: dotnetapp
          image: ggszgz/vueaws:teatro # Replace with the actual image tag
          ports:
            - containerPort: 80 # Replace with the port your Tetris game listen
